### ISSUE TITLE
async/await error: Unexpected token function

### ISSUE THREAD

**Issue by JulianKingman** [okgrow/meteor-promise#4]
I'm using the async/await method (as shown here: http://okgrow-promise.meteor.com/#example-three), and I'm getting an error. My code, simplified, is like this:

``` javascript
template.someTemplate.onRendered(async function(){
    var results = await Meteor.promise('someMethod');
    results.forEach(function(result){
        //do something here
    }
});
```

The error is "Unexpected token function" (it looks like it's not liking the 'async' before the function). I have grigio:babel and okgrow:promise, should this be working?

Thanks!

**Comment by deanrad** [comment]
Is it in a file with extension `.es6.js` or `.es6` ? It sounds like it's not getting picked up by babel.

**Comment by JulianKingman** [comment]
Hah, yep, that would do it. I should have taken a closer look at the console, changing it to .es6.js fixed it. This makes things so much easier :)
