### ISSUE TITLE
Deprecate and recommend deanius:promise

### ISSUE THREAD

**Issue by richb-hanover** [okgrow/meteor-promise#6]
How are this version of meteor-promise and the deanius version (https://github.com/deanius/meteor-promise) related?

It appears that the deanius version has been worked on more recently - it is preferred?

**Comment by pauldowman** [comment]
Yes, thanks, that's been on our to-do list. This package should have no functionality but depend on (imply) deanius:promise too.

**Comment by richb-hanover** [comment]
Thanks for the speedy response. I'm not sure what you mean by, "This package should have no functionality..." 
- Does this mean that it provides no functionality beyond deanius:promise?
- Is there another library/package that I should look to?

**Comment by pauldowman** [comment]
What I mean is that in addition to noting it in the readme, we'll publish a new version of this package that depends on (using [imply](http://docs.meteor.com/#/full/pack_api_imply)) the current version of deanius:promise. So anyone who hasn't got around to removing this package and replacing it with deanius:promise will get deanius:promise anyway.

**Comment by richb-hanover** [comment]
Thanks!

**Comment by pauldowman** [comment]
I'm re-opening this to remind us to do this ASAP.

**Comment by deanrad** [comment]
Do y'all have any suggestions on where I could host the docs now that free meteor hosting is gone?

**Comment by jamielob** [comment]
@deanius I'll drop you an email with who to contact at MDG about getting on the Galaxy Package Demo program - free hosting to host the demo for popular community packages.

**Comment by deanrad** [comment]
Got it - thanks @jamielob
